export const RED_COLORS = {
  FIRST: '#FA752B',
  SECOND: '#DE4D26',
  THIRD: '#F44336',
  FORTH: '#DE2658',
  FIFTH: '#FA2BCB',
};

export const PURPLE_COLORS = {
  FIRST: '#FA2B77',
  SECOND: '#DE26C5',
  THIRD: '#CE36F4',
  FOURTH: '#8726DE',
  FIFTH: '#5F2BFA',
};

export const BLUE_COLORS = {
  FIRST: '#0D4BFF',
  SECOND: '#0C7EE8',
  THIRD: '#00C8FF',
  FORTH: '#0CE8DD',
  FIFTH: '#0DFFAE',
};

export const GREEN_COLORS = {
  FIRST: '#2BFAF3',
  SECOND: '#26DEA3',
  THIRD: '#36F482',
  FORTH: '#26DE3B',
  FIFTH: '#55FA2B',
};

export const YELLOW_COLORS = {
  FIRST: '#FFEE30',
  SECOND: '#E8C62C',
  THIRD: '#FFC93D',
  FORTH: '#E8A02C',
  FIFTH: '#FF9530',
};

export const COLORS = {
  WHITE: '#FFFFFF',
  WHITE_BG: '#353535',
  GREY_BG: '#2A2A2A',
  GREY: '#b9b9b9',
  LIGHT_GREY: '#6a6a6a',
  PLACEHOLDER: '#989898',
  LIGHT_BREAK_LINE: '#2F2F2F',
  INPUT_BG: '#F5F5F5',
  BUTTON_BG: '#F2F2F2',
  BG: '#1F1F1F',
  RED: RED_COLORS.THIRD,
  BLUE: BLUE_COLORS.THIRD,
  ORANGE: YELLOW_COLORS.THIRD,
  DARK_GREEN: '#3DB39E',
  WHITE_GREEN: '#74E6CF',
  LIGHT_GREEN: '#9ED9CF',
  QUICK_TASK_BUTTON: '#3F3F3F',
};

export const AVAILABLE_COLORS = [
  ...Object.values(RED_COLORS),
  ...Object.values(PURPLE_COLORS),
  ...Object.values(BLUE_COLORS),
  ...Object.values(GREEN_COLORS),
  ...Object.values(YELLOW_COLORS),
];
